no good might,wight,fight,tight
no good rover,mover,roger,rower
no good rover,mower,roger,rower
no good brake,grave,grape,graze
no good hatch,catch,patch,batch
no good stage,stake,stave,state
no good grave,grape,brave,graze
no good jaunt,taunt,gaunt,vaunt
no good batty,patty,tatty,fatty
no good batty,tatty,fatty,catty
no good gamer,gazer,waver,wafer
no good break,creak,freak,wreak
no good paper,racer,waver,wafer
