version: 2.1

jobs:
  build:
    docker:
      - image: domslee/gcctbb:x86
    steps:
      - checkout
      - run:
          command: |
            make -j bin/test bin/solve
  test:
    docker:
      - image: domslee/gcctbb:x86
    steps:
      - checkout
      - run:
          command: |
            make -j bin/test
            mkdir -p databases
            export IGNORE_BIGTESTS=1
            ./bin/test

workflows:
  build_and_test:
    jobs:
      - build
      - test